# System-wide .bashrc file for interactive bash(1) shells.

# To enable the settings / commands in this file for login shells as well,
# this file has to be sourced in /etc/profile.

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
#shopt -s checkwinsize

# set variable identifying the chroot you work in (used in the prompt below)
#if [ -z "$debian_chroot" -a -r /etc/debian_chroot ]; then
#    debian_chroot=$(cat /etc/debian_chroot)
#fi

# Tirar o "beep" do console
set bell-style none
setterm -bfreq 0

# Tirar o "beep" do X
#xset -b 2> /dev/null 

# You may uncomment the following lines if you want `ls' to be colorized:
export LS_OPTIONS='-h --color=auto'
alias ls='ls $LS_OPTIONS'
alias cds='cd /etc/init.d ; ls'

# Enable VIM
alias vi='vim'

# Enable SVN Editing with VIM.
export SVN_EDITOR=vim

# Enable colourrc
if [ -f /etc/colourrc ]; then
     eval `dircolors /etc/colourrc`
fi

# Some more alias to avoid making mistakes:
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Enable bash completion in interactive shells
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi
